name: Build Windows exe

on:
  workflow_dispatch:

jobs:
  build-windows-exe:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.24.2'

      - name: Install dependencies
        run: flutter pub get

      - name: Generate localization
        run: dart localization/generator.dart

      - name: Set update check flag
        shell: pwsh
        run: |
          $filePath = Get-ChildItem -Path . -Filter "update_check_flag_file.dart" -Recurse | Select-Object -First 1
          if ($filePath) {
            echo "const updateCheckFlag = true;" > $filePath.FullName
          } else {
            mkdir -p lib/utils
            echo "const updateCheckFlag = true;" > lib/utils/update_check_flag_file.dart
          }

      - name: Build Windows Release
        run: flutter build windows --release

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Harmony-Music-Windows-Portable
          # Esta ruta con asteriscos busca la carpeta Release en cualquier subcarpeta
          path: build/windows/*/Release/
          if-no-files-found: error
